<?xml version="1.0"?>
<!-- Xacro-based description for 6-DOF arm with ros_control and Gazebo plugin -->
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="six_dof_arm">

  <!-- Properties for dimensions -->
  <xacro:property name="base_h" value="0.05" />
  <xacro:property name="base_r" value="0.05" />
  <xacro:property name="l1_len" value="0.30" />
  <xacro:property name="l2_len" value="0.30" />
  <xacro:property name="l3_len" value="0.30" />
  <xacro:property name="l4_len" value="0.20" />
  <xacro:property name="l5_len" value="0.10" />
  <xacro:property name="tool_len" value="0.10" />
  <xacro:property name="big_r" value="0.03" />
  <xacro:property name="small_r" value="0.02" />

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_h/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_h}" radius="${base_r}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_h/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_h}" radius="${base_r}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${base_h/2}" rpy="0 0 0"/>
      <mass value="2.0"/>
      <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- Link 1 & Joint 1 -->
  <link name="link_1">
    <visual>
      <origin xyz="0 0 ${l1_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${l1_len}" radius="${big_r}"/></geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${l1_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${l1_len}" radius="${big_r}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${l1_len/2}" rpy="0 0 0"/>
      <mass value="1.06"/>
      <inertia ixx="0.008191" iyy="0.008191" izz="0.000477" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  <joint name="joint_1" type="revolute">
    <parent link="base_link"/>
    <child link="link_1"/>
    <origin xyz="0 0 ${base_h}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.1416" upper="3.1416" effort="10" velocity="1.0"/>
  </joint>

  <!-- Link 2 & Joint 2 -->
  <link name="link_2">
    <visual>
      <origin xyz="0 0 ${l2_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${l2_len}" radius="${big_r}"/></geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${l2_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${l2_len}" radius="${big_r}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${l2_len/2}" rpy="0 0 0"/>
      <mass value="1.06"/>
      <inertia ixx="0.008191" iyy="0.008191" izz="0.000477" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  <joint name="joint_2" type="revolute">
    <parent link="link_1"/>
    <child link="link_2"/>
    <origin xyz="0 0 ${l1_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.5708" upper="1.5708" effort="10" velocity="1.0"/>
  </joint>

  <!-- Link 3 & Joint 3 -->
  <link name="link_3">
    <visual>
      <origin xyz="0 0 ${l3_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${l3_len}" radius="${big_r}"/></geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${l3_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${l3_len}" radius="${big_r}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${l3_len/2}" rpy="0 0 0"/>
      <mass value="1.06"/>
      <inertia ixx="0.008191" iyy="0.008191" izz="0.000477" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  <joint name="joint_3" type="revolute">
    <parent link="link_2"/>
    <child link="link_3"/>
    <origin xyz="0 0 ${l2_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.5708" upper="1.5708" effort="10" velocity="1.0"/>
  </joint>

  <!-- Link 4 & Joint 4 -->
  <link name="link_4">
    <visual>
      <origin xyz="0 0 ${l4_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${l4_len}" radius="${small_r}"/></geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${l4_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${l4_len}" radius="${small_r}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${l4_len/2}" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.002" iyy="0.002" izz="0.0001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  <joint name="joint_4" type="revolute">
    <parent link="link_3"/>
    <child link="link_4"/>
    <origin xyz="0 0 ${l3_len}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.1416" upper="3.1416" effort="5" velocity="1.0"/>
  </joint>

  <!-- Link 5 & Joint 5 -->
  <link name="link_5">
    <visual>
      <origin xyz="0 0 ${l5_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${l5_len}" radius="${small_r}"/></geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${l5_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${l5_len}" radius="${small_r}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${l5_len/2}" rpy="0 0 0"/>
      <mass value="0.3"/>
      <inertia ixx="0.0005" iyy="0.0005" izz="0.00002" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  <joint name="joint_5" type="revolute">
    <parent link="link_4"/>
    <child link="link_5"/>
    <origin xyz="0 0 ${l4_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.5708" upper="1.5708" effort="5" velocity="1.0"/>
  </joint>

  <!-- Tool link & Joint 6 -->
  <link name="tool_link">
    <visual>
      <origin xyz="0 0 ${tool_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${tool_len}" radius="${small_r}"/></geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${tool_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${tool_len}" radius="${small_r}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${tool_len/2}" rpy="0 0 0"/>
      <mass value="0.2"/>
      <inertia ixx="0.0002" iyy="0.0002" izz="0.00001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  <joint name="joint_6" type="revolute">
    <parent link="link_5"/>
    <child link="tool_link"/>
    <origin xyz="0 0 ${l5_len}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.1416" upper="3.1416" effort="5" velocity="1.0"/>
  </joint>

  <!-- Gazebo ros_control plugin -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
  </gazebo>

  <!-- Transmission macro -->
  <xacro:macro name="transmission_block" params="joint actuator">
    <transmission name="${joint}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${joint}">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="${actuator}">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <!-- Instantiate transmissions for each joint -->
  <xacro:transmission_block joint="joint_1" actuator="joint_1_motor"/>
  <xacro:transmission_block joint="joint_2" actuator="joint_2_motor"/>
  <xacro:transmission_block joint="joint_3" actuator="joint_3_motor"/>
  <xacro:transmission_block joint="joint_4" actuator="joint_4_motor"/>
  <xacro:transmission_block joint="joint_5" actuator="joint_5_motor"/>
  <xacro:transmission_block joint="joint_6" actuator="joint_6_motor"/>

</robot>
