joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05

  gains:
    joint_1: {p: 100, i: 0, d: 10}
    joint_2: {p:  80, i: 0, d:  8}
    joint_3: {p:  60, i: 0, d:  6}
    joint_4: {p:  40, i: 0, d:  4}
    joint_5: {p:  20, i: 0, d:  2}
    joint_6: {p:  10, i: 0, d:  1}
